name: Kotlin CI

# ↓を参考にAction作りました
# https://docs.github.com/ja/actions/guides/building-and-testing-java-with-gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport
      - name: Test with Gradle
        run: ./gradlew test
      # codecov - https://github.com/codecov/codecov-action#example-workflowyml-with-codecov-action
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

      # "build/reports/jacoco"をartifactに追加
      - name: Archive coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html
      # Cleanup
      - name: Cleanup Gradle Cache
        # https://docs.github.com/ja/actions/guides/building-and-testing-java-with-gradle
        # GitHub Actions でキャッシュされないように Gradle キャッシュからいくつかのファイルを削除
        # これらのファイルをGitHub Actionsのキャッシュからリストアすると、将来のビルドで問題が生じるかもしれない。
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
